services:
  db:
    image: postgres:16
    container_name: nesventory_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nesventory
      POSTGRES_PASSWORD: nesventory
      POSTGRES_DB: nesventory
    volumes:
      - nesventory_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nesventory_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app/app:ro

volumes:
  nesventory_db_data:
